export const ROUTE = 'ROUTE'
export const CONNECT = 'CONNECT'
export const DISCONNECT = 'DISCONNECT'
export const LOCAL_STREAM = 'LOCAL_STREAM'
export const USE_OTG_CAMERA = 'USE_OTG_CAMERA'
export const SET_ROOM_ID = 'SET_ROOM_ID'
export const ADD_STREAM = 'ADD_STREAM'
export const REMOVE_STREAM = 'REMOVE_STREAM'